name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - ipyleaflet
  - pprint
  - ipywidgets
  - random
  - json
  - os
  - requests
  - shapely
